// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.sc.msg;

public final class MessageBuf {
  private MessageBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BindAccountReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BindAccountReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *第三方平台编号
     * </pre>
     *
     * <code>optional int32 platformType = 1;</code>
     */
    int getPlatformType();

    /**
     * <pre>
     *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
     * </pre>
     *
     * <code>optional string code = 2;</code>
     */
    String getCode();
    /**
     * <pre>
     *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
     * </pre>
     *
     * <code>optional string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <pre>
     *绑定的账号的类型；0：玩家ID；1：玩家字符串唯一账号
     * </pre>
     *
     * <code>optional int32 bindIdType = 3;</code>
     */
    int getBindIdType();

    /**
     * <pre>
     *要绑定的账号
     * </pre>
     *
     * <code>optional string bindId = 4;</code>
     */
    String getBindId();
    /**
     * <pre>
     *要绑定的账号
     * </pre>
     *
     * <code>optional string bindId = 4;</code>
     */
    com.google.protobuf.ByteString
        getBindIdBytes();

    /**
     * <pre>
     *不覆盖已有账号；1：强制覆盖已有账号
     * </pre>
     *
     * <code>optional int32 coverFlag = 5;</code>
     */
    int getCoverFlag();
  }
  /**
   * Protobuf type {@code BindAccountReq}
   */
  public  static final class BindAccountReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BindAccountReq)
      BindAccountReqOrBuilder {
    // Use BindAccountReq.newBuilder() to construct.
    private BindAccountReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BindAccountReq() {
      platformType_ = 0;
      code_ = "";
      bindIdType_ = 0;
      bindId_ = "";
      coverFlag_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BindAccountReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              platformType_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 24: {

              bindIdType_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              bindId_ = s;
              break;
            }
            case 40: {

              coverFlag_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageBuf.internal_static_BindAccountReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageBuf.internal_static_BindAccountReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageBuf.BindAccountReq.class, MessageBuf.BindAccountReq.Builder.class);
    }

    public static final int PLATFORMTYPE_FIELD_NUMBER = 1;
    private int platformType_;
    /**
     * <pre>
     *第三方平台编号
     * </pre>
     *
     * <code>optional int32 platformType = 1;</code>
     */
    public int getPlatformType() {
      return platformType_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile Object code_;
    /**
     * <pre>
     *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
     * </pre>
     *
     * <code>optional string code = 2;</code>
     */
    public String getCode() {
      Object ref = code_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
     * </pre>
     *
     * <code>optional string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BINDIDTYPE_FIELD_NUMBER = 3;
    private int bindIdType_;
    /**
     * <pre>
     *绑定的账号的类型；0：玩家ID；1：玩家字符串唯一账号
     * </pre>
     *
     * <code>optional int32 bindIdType = 3;</code>
     */
    public int getBindIdType() {
      return bindIdType_;
    }

    public static final int BINDID_FIELD_NUMBER = 4;
    private volatile Object bindId_;
    /**
     * <pre>
     *要绑定的账号
     * </pre>
     *
     * <code>optional string bindId = 4;</code>
     */
    public String getBindId() {
      Object ref = bindId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bindId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *要绑定的账号
     * </pre>
     *
     * <code>optional string bindId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBindIdBytes() {
      Object ref = bindId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bindId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COVERFLAG_FIELD_NUMBER = 5;
    private int coverFlag_;
    /**
     * <pre>
     *不覆盖已有账号；1：强制覆盖已有账号
     * </pre>
     *
     * <code>optional int32 coverFlag = 5;</code>
     */
    public int getCoverFlag() {
      return coverFlag_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (platformType_ != 0) {
        output.writeInt32(1, platformType_);
      }
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (bindIdType_ != 0) {
        output.writeInt32(3, bindIdType_);
      }
      if (!getBindIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bindId_);
      }
      if (coverFlag_ != 0) {
        output.writeInt32(5, coverFlag_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (platformType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, platformType_);
      }
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (bindIdType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bindIdType_);
      }
      if (!getBindIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bindId_);
      }
      if (coverFlag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, coverFlag_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageBuf.BindAccountReq)) {
        return super.equals(obj);
      }
      MessageBuf.BindAccountReq other = (MessageBuf.BindAccountReq) obj;

      boolean result = true;
      result = result && (getPlatformType()
          == other.getPlatformType());
      result = result && getCode()
          .equals(other.getCode());
      result = result && (getBindIdType()
          == other.getBindIdType());
      result = result && getBindId()
          .equals(other.getBindId());
      result = result && (getCoverFlag()
          == other.getCoverFlag());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PLATFORMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformType();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + BINDIDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBindIdType();
      hash = (37 * hash) + BINDID_FIELD_NUMBER;
      hash = (53 * hash) + getBindId().hashCode();
      hash = (37 * hash) + COVERFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getCoverFlag();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageBuf.BindAccountReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageBuf.BindAccountReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageBuf.BindAccountReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageBuf.BindAccountReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageBuf.BindAccountReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageBuf.BindAccountReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageBuf.BindAccountReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageBuf.BindAccountReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageBuf.BindAccountReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageBuf.BindAccountReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageBuf.BindAccountReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BindAccountReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BindAccountReq)
        MessageBuf.BindAccountReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageBuf.internal_static_BindAccountReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageBuf.internal_static_BindAccountReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageBuf.BindAccountReq.class, MessageBuf.BindAccountReq.Builder.class);
      }

      // Construct using com.sc.MessageBuf.BindAccountReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        platformType_ = 0;

        code_ = "";

        bindIdType_ = 0;

        bindId_ = "";

        coverFlag_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageBuf.internal_static_BindAccountReq_descriptor;
      }

      public MessageBuf.BindAccountReq getDefaultInstanceForType() {
        return MessageBuf.BindAccountReq.getDefaultInstance();
      }

      public MessageBuf.BindAccountReq build() {
        MessageBuf.BindAccountReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageBuf.BindAccountReq buildPartial() {
        MessageBuf.BindAccountReq result = new MessageBuf.BindAccountReq(this);
        result.platformType_ = platformType_;
        result.code_ = code_;
        result.bindIdType_ = bindIdType_;
        result.bindId_ = bindId_;
        result.coverFlag_ = coverFlag_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageBuf.BindAccountReq) {
          return mergeFrom((MessageBuf.BindAccountReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageBuf.BindAccountReq other) {
        if (other == MessageBuf.BindAccountReq.getDefaultInstance()) return this;
        if (other.getPlatformType() != 0) {
          setPlatformType(other.getPlatformType());
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (other.getBindIdType() != 0) {
          setBindIdType(other.getBindIdType());
        }
        if (!other.getBindId().isEmpty()) {
          bindId_ = other.bindId_;
          onChanged();
        }
        if (other.getCoverFlag() != 0) {
          setCoverFlag(other.getCoverFlag());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageBuf.BindAccountReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageBuf.BindAccountReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int platformType_ ;
      /**
       * <pre>
       *第三方平台编号
       * </pre>
       *
       * <code>optional int32 platformType = 1;</code>
       */
      public int getPlatformType() {
        return platformType_;
      }
      /**
       * <pre>
       *第三方平台编号
       * </pre>
       *
       * <code>optional int32 platformType = 1;</code>
       */
      public Builder setPlatformType(int value) {

        platformType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *第三方平台编号
       * </pre>
       *
       * <code>optional int32 platformType = 1;</code>
       */
      public Builder clearPlatformType() {

        platformType_ = 0;
        onChanged();
        return this;
      }

      private Object code_ = "";
      /**
       * <pre>
       *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
       * </pre>
       *
       * <code>optional string code = 2;</code>
       */
      public String getCode() {
        Object ref = code_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
       * </pre>
       *
       * <code>optional string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
       * </pre>
       *
       * <code>optional string code = 2;</code>
       */
      public Builder setCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
       * </pre>
       *
       * <code>optional string code = 2;</code>
       */
      public Builder clearCode() {

        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通过第三方登录获得的唯一码，服务器用来去第三方获取登录相关信息
       * </pre>
       *
       * <code>optional string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        code_ = value;
        onChanged();
        return this;
      }

      private int bindIdType_ ;
      /**
       * <pre>
       *绑定的账号的类型；0：玩家ID；1：玩家字符串唯一账号
       * </pre>
       *
       * <code>optional int32 bindIdType = 3;</code>
       */
      public int getBindIdType() {
        return bindIdType_;
      }
      /**
       * <pre>
       *绑定的账号的类型；0：玩家ID；1：玩家字符串唯一账号
       * </pre>
       *
       * <code>optional int32 bindIdType = 3;</code>
       */
      public Builder setBindIdType(int value) {

        bindIdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定的账号的类型；0：玩家ID；1：玩家字符串唯一账号
       * </pre>
       *
       * <code>optional int32 bindIdType = 3;</code>
       */
      public Builder clearBindIdType() {

        bindIdType_ = 0;
        onChanged();
        return this;
      }

      private Object bindId_ = "";
      /**
       * <pre>
       *要绑定的账号
       * </pre>
       *
       * <code>optional string bindId = 4;</code>
       */
      public String getBindId() {
        Object ref = bindId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bindId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *要绑定的账号
       * </pre>
       *
       * <code>optional string bindId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBindIdBytes() {
        Object ref = bindId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bindId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *要绑定的账号
       * </pre>
       *
       * <code>optional string bindId = 4;</code>
       */
      public Builder setBindId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        bindId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要绑定的账号
       * </pre>
       *
       * <code>optional string bindId = 4;</code>
       */
      public Builder clearBindId() {

        bindId_ = getDefaultInstance().getBindId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要绑定的账号
       * </pre>
       *
       * <code>optional string bindId = 4;</code>
       */
      public Builder setBindIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        bindId_ = value;
        onChanged();
        return this;
      }

      private int coverFlag_ ;
      /**
       * <pre>
       *不覆盖已有账号；1：强制覆盖已有账号
       * </pre>
       *
       * <code>optional int32 coverFlag = 5;</code>
       */
      public int getCoverFlag() {
        return coverFlag_;
      }
      /**
       * <pre>
       *不覆盖已有账号；1：强制覆盖已有账号
       * </pre>
       *
       * <code>optional int32 coverFlag = 5;</code>
       */
      public Builder setCoverFlag(int value) {

        coverFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *不覆盖已有账号；1：强制覆盖已有账号
       * </pre>
       *
       * <code>optional int32 coverFlag = 5;</code>
       */
      public Builder clearCoverFlag() {

        coverFlag_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BindAccountReq)
    }

    // @@protoc_insertion_point(class_scope:BindAccountReq)
    private static final MessageBuf.BindAccountReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageBuf.BindAccountReq();
    }

    public static MessageBuf.BindAccountReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BindAccountReq>
        PARSER = new com.google.protobuf.AbstractParser<BindAccountReq>() {
      public BindAccountReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BindAccountReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BindAccountReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BindAccountReq> getParserForType() {
      return PARSER;
    }

    public MessageBuf.BindAccountReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BindAccountReq_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BindAccountReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\"k\n\016BindAccountReq\022\024\n\014pla" +
      "tformType\030\001 \001(\005\022\014\n\004code\030\002 \001(\t\022\022\n\nbindIdT" +
      "ype\030\003 \001(\005\022\016\n\006bindId\030\004 \001(\t\022\021\n\tcoverFlag\030\005" +
      " \001(\005B\030\n\ncom.sc.msgB\nMessageBufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BindAccountReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BindAccountReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BindAccountReq_descriptor,
        new String[] { "PlatformType", "Code", "BindIdType", "BindId", "CoverFlag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
